services:
  nginx:
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - secrets/.env
    volumes:
      - wp:/var/www/html
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: on-failure
  wordpress:
    depends_on:
      - mariadb
      - redis
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - secrets/.db.env
      - secrets/.env
    volumes:
      - wp:/var/www/html
    restart: on-failure

  mariadb:
    networks:
      - inception
    env_file:
      - secrets/.db.env
    build:
      context: requirements/mariaDB
      dockerfile: Dockerfile
    volumes:
      - mdb:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  redis:
    networks:
      - inception
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    restart: on-failure
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  ftp:
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    ports:
      - "21:21"
      - "20:20"
      - "21100-21110:21100-21110"
    volumes:
      - wp:/var/ftp/wordpress
    env_file:
      - secrets/.ftp.env
    restart: on-failure
  adminer:
    networks:
      - inception
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    restart: on-failure
  portfolio:
    build:
      context: requirements/bonus/portfolio
      dockerfile: Dockerfile
    ports:
      - "8081:5000"
    restart: on-failure
  uptime-kuma:
    build:
      context: requirements/bonus/uptime-kuma
      dockerfile: Dockerfile
    ports:
      - "8082:3001"
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  mdb:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/eebert/data/mariadb
  wp:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/eebert/data/wordpress